version: "3.8"

services:
  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env
    networks:
      - flask-app-network
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - flask-app-network
    ports:
      - 8080:80
    restart: always
    depends_on:
      db:
        condition: service_started
        restart: true
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - flask-app-network
    restart: always
  
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask-app
    env_file:
      - .env
    networks: 
      - flask-app-network
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
networks:
  flask-app-network:
    driver: bridge
volumes:
  db-data:
    driver: local
